Creazione messaggio di benvenuto e scelta colore shell
zSavT/lazy-shell pull request #8
Opened 2021-04-01 21:52 UTC by zSavT

Se viene approvata la struttura, inserirò altri colori e combinazioni per la shell.

2021-04-01 23:10 UTC, AlessandroCarella requested changes
c'è solo un problema, dobbiamo formattare i file / la divisione dei file tutti nello stesso modo:
tu hai creato un file modulX.h e un file moduloX.cpp mentre io sto mettendo tutto nel .h
secondo me è meglio cosi pero dimmi tu come preferisci fare e cambio i miei file nel caso (o li cambi tu)

2021-04-01 23:13 UTC, zSavT commented
> c'è solo un problema, dobbiamo formattare i file / la divisione dei file tutti nello stesso modo:
> tu hai creato un file modulX.h e un file moduloX.cpp mentre io sto mettendo tutto nel .h
> secondo me è meglio cosi pero dimmi tu come preferisci fare e cambio i miei file nel caso (o li cambi tu)

Ma tu stai lavorando con delle classi, io al momento no.

2021-04-01 23:16 UTC, AlessandroCarella commented
Hum si ma preferirei lasciare tutto nel file moduloX.h anche se dovessi aggiungere delle funzioni.

2021-04-02 08:27 UTC, zSavT commented
> Hum si ma preferirei lasciare tutto nel file moduloX.h anche se dovessi aggiungere delle funzioni.

Si ma così non sono più Header file, ho suddiviso in più file solo per una questione di comodità. Un header file non deve avere al suo interno una implementazione di una funzione ma solo la sua dichiarazione.

2021-04-02 10:03 UTC, AlessandroCarella approved these changes
Tutto ok

2021-04-02 10:04 UTC, merged